import { ptBR } from '@clerk/localizations'
import { ClerkProvider } from '@clerk/nextjs'
import { dark } from '@clerk/themes'
import { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <ClerkProvider 
      localization={ptBR} 
      appearance={{
        baseTheme: dark, 
        elements: {
          formButtonPrimary: 'bg-purple-800 hover:bg-purple-700',
          formFieldInput__emailAddress: 'focus:border-purple-800',
          providerIcon__atlassian: 'text-purple-800 fill-purple-800',
          formFieldAction: 'text-purple-800',
        }
      }}>
      <html lang="pt-br">
        <body className={inter.className}>
          <div className='h-screen flex justify-center items-center'>
            {children}
          </div>
          </body>
      </html>
    </ClerkProvider>
    
  )
}
